# Generated by Django 4.1.2 on 2022-10-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('h_entrada', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('h_salida', models.DateTimeField()),
                ('n_horas', models.BigIntegerField()),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
    ]
